apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sb-#cluser_uid#-cassandra
  name: sb-#cluser_uid#-cassandra
spec:
  containers:
  - args:
    - /run.sh
    resources:
      limits:
        cpu: "0.1"
    image: 172.30.188.59:5000/yepeng/cassandra-openshift-orchestration:latest
    name: sb-#cluser_uid#-cassandra
    ports:
    - name: cql
      containerPort: 9042
    - name: thrift
      containerPort: 9160
    volumeMounts:
    - name: data
      mountPath: /cassandra_data
    env:
    - name: MAX_HEAP_SIZE
      value: 512M
    - name: HEAP_NEWSIZE
      value: 100M
    - name: cluster_name
      value: sb-#cluser_uid#-cassandra
    - name: CASSANDRA_SERVICE
      value: sb-#cluser_uid#-cassandra
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
  volumes:
    - name: data
      emptyDir: {}


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sb-#cluser_uid#-cassandra
  name: sb-#cluser_uid#-cassandra
spec:
  ports:
    - port: 9042
  selector:
    app: sb-#cluser_uid#-cassandra

---

#Route to client
apiVersion: v1
kind: Route
metadata:
  name: sb-#cluser_uid#-cassandra
spec:
  host: sb-#cluser_uid#-cassandra.app.dataos.io
  to:
    kind: Service
    name: sb-#cluser_uid#-cassandra
