apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: sb-#cluster_uid#-cassandra
  name: sb-#cluster_uid#-cassandra
spec:
  replicas: 4
  selector:
      app: sb-#cluster_uid#-cassandra
  template:
    metadata:
      labels:
        app: sb-#cluster_uid#-cassandra
    spec:
      containers:
        - command:
            - /run.sh
          resources:
            limits:
              cpu: 0.1
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_SERVICE
              value: sb-#cluster_uid#-cassandra
            - name: cluster_name
              value: sb-#cluster_uid#-cassandra
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: 172.30.188.59:5000/yepeng/cassandra-openshift-orchestration:latest
          name: sb-#cluster_uid#-cassandra
          ports:
            - containerPort: 9042
              name: cql
            - containerPort: 9160
              name: thrift
          volumeMounts:
            - mountPath: /cassandra_data
              name: data
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - /status_check.sh
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sb-#cluster_uid#-cassandra
  name: sb-#cluster_uid#-cassandra
spec:
  ports:
    - port: 9042
  selector:
    app: sb-#cluster_uid#-cassandra

---

#Route to client
apiVersion: v1
kind: Route
metadata:
  name: sb-#cluster_uid#-cassandra
spec:
  host: sb-#cluster_uid#-cassandra.app.dataos.io
  to:
    kind: Service
    name: sb-#cluster_uid#-cassandra
